version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "studentgrade"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mtg676jfy4a4"
s3_prefix = "studentgrade"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
